### ISSUE TITLE
TOML formatter in the CI

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1751]
**Issue summary**

Let's save some reviewers' time and put our rules regarding TOML files as code!
It'd be great to explore a tool like this: https://github.com/tamasfe/taplo and put it into work in Forest repo.

**Other information and links**

https://taplo.tamasfe.dev/cli/usage/formatting.html
https://taplo.tamasfe.dev/configuration/formatter-options.html

**Comment by lemmih** [comment]
Configuration proposal:
```toml
[formatting]
align_entries     = true
column_width      = 120
array_auto_expand = false

[[rule]]
keys = ["dependencies", "dev-dependencies"]

[rule.formatting]
reorder_keys = true
```
