### ISSUE TITLE
Cancel workflows for PRs from forked repositories

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1988]
**Issue summary**

As @hanabi1224 suggested, there's a way to make the cancellation more robust. We should implement his proposal or something like it.

~~Right now we cancel all previous CI runs on each commit to every branch. This makes sense for PRs where we don't want to waste resources when multiple commits are pushed in quick succession. But for the `main` branch, we would like each commit to be tested and receive a green checkmark.~~

~~We can disable the `cancel-workflow-action` step on the `main` branch by adding something like `if: ${{ github.event_name == 'pull_request' }}` to the workflow.~~

**Other information and links**

**Comment by hanabi1224** [comment]
Besides this one, I think the current setup does not work for PRs from fork repos either per their [doc](https://github.com/styfle/cancel-workflow-action#advanced-pull-requests-from-forks).

I think it's better to remove the steps from individual workflows and make a standalone one for cancelling stale workflow runs, maybe `cancel-stale.yml`

here's one I propose

```yaml
# https://github.com/marketplace/actions/cancel-workflow-action#advanced-pull-requests-from-forks
name: Cancel stale workflows
on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_runbranchesbranches-ignore
  workflow_run:
    workflows:
      - "Build and publish Forest Docker image"
      - "Docs"
      - "Rust"
      - "Scripts"
    types:
      - requested
    branches:
      - "!main"
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.1
        with:
          workflow_id: ${{ github.event.workflow.id }}
          # https://github.com/styfle/cancel-workflow-action#advanced-all-but-latest
          all_but_latest: true
```
