### ISSUE TITLE
Long-running node excessive memory usage

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4534]
## Issue summary

An issue with a long-running calibnet node surfaced in which Forest is using significantly more memory than it should. This might be related to https://github.com/ChainSafe/forest/issues/4346

![image](https://github.com/user-attachments/assets/4f07f9a8-ab15-4661-b973-1a5433fa0eee)

We can see that the memory grows up until 13 GiB, then the node likely gets restarted (can you please confirm @samuelarogbonlo?). Now, this is nowhere close our expectations where the calibnet node should run easily on a RPi4.

Is there a memory leak?

[logs.txt](https://github.com/user-attachments/files/16249088/logs.txt)

```toml
[client]
#Controls whether the keystore is encrypted
encrypt_keystore = false
data_dir = "/home/forest/forest_data"
enable_rpc = true
enable_metrics_endpoint = true
metrics_address = "127.0.0.1:6116"
rpc_address = "0.0.0.0:2345"

[network]
listening_multiaddrs = ["/ip4/0.0.0.0/tcp/34000"]
#Kademlia option enforce p2p connections.
kademlia = true
#Amount of peers the node should maintain a connection with
#Helps in syncing ( moderate value to not be exceeded)
target_peer_count = 5000
```

Forest `v0.19.0`, calibration network bootstrap node
